//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MESwebservice.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.webxml.com.cn/webservices/qqOnlineWebService.asmx")]
        public string MESwebservice_QQwebsev_qqOnlineWebService {
            get {
                return ((string)(this["MESwebservice_QQwebsev_qqOnlineWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ly5mesp178:50200/atlmeswebservice/MiCustomDCForCellServiceService")]
        public string MESwebservice_OCV_MiCustomDCForCellServiceService {
            get {
                return ((string)(this["MESwebservice_OCV_MiCustomDCForCellServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ly5mesp178:50200/atlmeswebservice/MiBatchStartAndGetParameterServiceServic" +
            "e")]
        public string MESwebservice_OCVgetData_MiBatchStartAndGetParameterServiceService {
            get {
                return ((string)(this["MESwebservice_OCVgetData_MiBatchStartAndGetParameterServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ly5mesp180:50400/atlmeswebservice/MiReleaseSfcWithActivityServiceService")]
        public string MESwebservice_BlockReleaseSfc_MiReleaseSfcWithActivityServiceService {
            get {
                return ((string)(this["MESwebservice_BlockReleaseSfc_MiReleaseSfcWithActivityServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ly5mesp178:50200/atlmeswebservice/MiCheckInventoryAttributesServiceService" +
            "")]
        public string MESwebservice_BlockCheckinvent_MiCheckInventoryAttributesServiceService {
            get {
                return ((string)(this["MESwebservice_BlockCheckinvent_MiCheckInventoryAttributesServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ly5mesp180:50400/atlmeswebservice/MiAssembleAndCollectDataForSfcServiceSer" +
            "vice")]
        public string MESwebservice_BlockMiAssembleAndCollectData_MiAssembleAndCollectDataForSfcServiceService {
            get {
                return ((string)(this["MESwebservice_BlockMiAssembleAndCollectData_MiAssembleAndCollectDataForSfcService" +
                    "Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lymesp114.catlbattery.com:51600/atlmeswebservice/MachineIntegrationService" +
            "Service")]
        public string MESwebservice_BlocksfcComplete_MachineIntegrationServiceService {
            get {
                return ((string)(this["MESwebservice_BlocksfcComplete_MachineIntegrationServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lymesp114.catlbattery.com:51600/atlmeswebservice/MiFindCustomAndSfcDataSer" +
            "viceService")]
        public string MESwebservice_ChangePro_MiFindCustomAndSfcDataServiceService {
            get {
                return ((string)(this["MESwebservice_ChangePro_MiFindCustomAndSfcDataServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ly5mesp177:50100/atlmeswebservice/MiSFCAttriDataEntryServiceService")]
        public string MESwebservice_AttrDataEntry_MiSFCAttriDataEntryServiceService {
            get {
                return ((string)(this["MESwebservice_AttrDataEntry_MiSFCAttriDataEntryServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lymesap224.catlbattery.com:50100/atlmeswebservice/MiFindCustomAndSfcDataSe" +
            "rviceService")]
        public string MESwebservice_FindCusAndSfc_MiFindCustomAndSfcDataServiceService {
            get {
                return ((string)(this["MESwebservice_FindCusAndSfc_MiFindCustomAndSfcDataServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ly5mesp180:50400/atlmeswebservice/DataCollectForResourceFAIServiceService")]
        public string MESwebservice_CollectSfc_DataCollectForResourceFAIServiceService {
            get {
                return ((string)(this["MESwebservice_CollectSfc_DataCollectForResourceFAIServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lymesp114.catlbattery.com:51600/atlmeswebservice/MiFindCustomAndSfcDataSer" +
            "viceService")]
        public string MESwebservice_PoleArrival_MiFindCustomAndSfcDataServiceService {
            get {
                return ((string)(this["MESwebservice_PoleArrival_MiFindCustomAndSfcDataServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lymesp112.catlbattery.com:50400/atlmeswebservice/MiGetPrintContentServiceS" +
            "ervice")]
        public string MESwebservice_GetBarCodeInfo_MiGetPrintContentServiceService {
            get {
                return ((string)(this["MESwebservice_GetBarCodeInfo_MiGetPrintContentServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ly5mesp180:50400/atlmeswebservice/MiAssembleAndCollectDataForSfcServiceSer" +
            "vice")]
        public string MESwebservice_AssAndCollData_MiAssembleAndCollectDataForSfcServiceService {
            get {
                return ((string)(this["MESwebservice_AssAndCollData_MiAssembleAndCollectDataForSfcServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ly5mesp178:50200/atlmeswebservice/MiCheckBOMInventoryServiceService")]
        public string MESwebservice_CheckBomInventory_MiCheckBOMInventoryServiceService {
            get {
                return ((string)(this["MESwebservice_CheckBomInventory_MiCheckBOMInventoryServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ly5mesp180:50400/atlmeswebservice/MachineIntegrationServiceService")]
        public string MESwebservice_AutoWeight_MachineIntegrationServiceService {
            get {
                return ((string)(this["MESwebservice_AutoWeight_MachineIntegrationServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lymesp114.catlbattery.com:51600/atlmeswebservice/MiFindCustomAndSfcDataSer" +
            "viceService")]
        public string MESwebservice_ModuleEntry_MiFindCustomAndSfcDataServiceService {
            get {
                return ((string)(this["MESwebservice_ModuleEntry_MiFindCustomAndSfcDataServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lymesp114.catlbattery.com:51600/atlmeswebservice/MiFindCustomAndSfcDataSer" +
            "viceService")]
        public string MESwebservice_ShimEntry_MiFindCustomAndSfcDataServiceService {
            get {
                return ((string)(this["MESwebservice_ShimEntry_MiFindCustomAndSfcDataServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ly5mesp180:50400/atlmeswebservice/DataCollectForResourceFAIServiceService")]
        public string MESwebservice_ShimCollForSfc_DataCollectForResourceFAIServiceService {
            get {
                return ((string)(this["MESwebservice_ShimCollForSfc_DataCollectForResourceFAIServiceService"]));
            }
        }
    }
}
